#server:
#  port: 8081

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/springtest?serverTimezone=CST&useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: mysql
#    schema:
#      - classpath:department.sql
##      - classpath: resources/employee.sql
